import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import Header from "@/src/components/Header";
import Footer from "../components/Footer";
import { indexHtml } from "@/controllers/index"
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children, team, analytics, modal
}: Readonly<{
  children: React.ReactNode;
  team: React.ReactNode;
  analytics: React.ReactNode;
  modal: React.ReactNode;
}>) {
  const contentData = await indexHtml();
  return (
    <html lang="zh-CN">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} style={{ background: "#6e747a" }}>
        <AntdRegistry>
          <div>
            <Header></Header>
            <div>{children}</div>
            <Footer allData={contentData} ></Footer>
          </div>
        </AntdRegistry>
      </body>
    </html >
  );
}
