
import React from 'react'

import List from '@/src/components/list'

import type { Metadata } from "next";
export const metadata: Metadata = {
    title: "博客列表",
    description: "Generated by create next app",
};
export default function Page() {

    return (
        <div>
            <List></List>
        </div>
    )
}
